#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
import sys
from datetime import datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo


ROOT = Path(__file__).resolve().parents[2]
HUB = ROOT / "investment-intelligence-hub"
TZ = ZoneInfo("America/New_York")
X_POSTS_ROOT = HUB / "inbox/x_posts"
X_FILE_LIMIT = 10

SOURCE_QUALITY = {
    "daily_report": {
        "tier": "tier_2_daily_base",
        "score": 0.65,
        "reason": "Generated by the existing daily report workflow from market data, feed metadata, watchlist configuration, and current report logic.",
    },
    "ljg_invest_report": {
        "tier": "tier_3_deep_research",
        "score": 0.70,
        "reason": "Deep single-name ljg-invest style research note. Used as thesis-context input that still requires primary-source verification.",
    },
    "x_post": {
        "tier": "tier_4_user_captured_x",
        "score": 0.45,
        "reason": "User-captured X source from the curated Hub inbox. Claims require corroboration before research use.",
    },
    "x_markdown": {
        "tier": "tier_4_user_captured_x",
        "score": 0.45,
        "reason": "Explicit converted X Markdown source. Claims require corroboration before research use.",
    },
    "x_html": {
        "tier": "tier_4_user_captured_x",
        "score": 0.45,
        "reason": "Explicit converted X HTML source. Claims require corroboration before research use.",
    },
}

FORBIDDEN = re.compile(r"\b(buy|sell|trim|add|position size|price target)\b", re.I)
SENSITIVE_PATTERNS = [
    ("account amount", re.compile(r"\b(account value|account balance|portfolio value)\b", re.I)),
    ("holding quantity", re.compile(r"\b(shares|contracts|units)\s*[:=]?\s*\d+|\b\d+\s+(shares|contracts|units)\b", re.I)),
    ("cost basis", re.compile(r"\bcost basis\b|\bavg\.?\s*cost\b", re.I)),
    ("exact trading plan", re.compile(r"\bexact trading plan\b|\bstop loss\b|\blimit order\b", re.I)),
    ("tax detail", re.compile(r"\btax lot\b|\bcapital gains?\b|\btaxable\b", re.I)),
    ("banking/company sensitive information", re.compile(r"\bbank account\b|\brouting number\b|\bconfidential\b|\bapi key\b|\bsecret\b", re.I)),
    ("private personal notes", re.compile(r"\bprivate note\b|\bpersonal note\b", re.I)),
]
KNOWN_TICKERS = {
    "AAOI", "ALAB", "ANET", "AVGO", "CIEN", "COHR", "CRDO", "CSCO", "FOCI", "LITE",
    "LWLG", "MRVL", "NOK", "POET", "SIVE",
}


def rel(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT.resolve()))
    except ValueError:
        return str(path)


def as_path(value: str | None) -> Path | None:
    if not value:
        return None
    path = Path(value).expanduser()
    return path if path.is_absolute() else ROOT / path


def sha256(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def slug(value: str) -> str:
    normalized = re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_").lower()
    return normalized[:48] or "source"


def stable_source_id(date: str, source_type: str, path: Path) -> str:
    digest = hashlib.sha256(rel(path).encode("utf-8")).hexdigest()[:10]
    return f"src_{date}_{source_type}_{slug(path.stem)}_{digest}"


def write_jsonl(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "\n".join(json.dumps(row, ensure_ascii=False, separators=(",", ":")) for row in rows) + "\n",
        encoding="utf-8",
    )


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def read_title(path: Path, fallback: str) -> str:
    for line in read_text(path).splitlines()[:20]:
        stripped = line.strip()
        if stripped.lower().startswith("#+title:"):
            return stripped.split(":", 1)[1].strip()
        if stripped.lower().startswith("title:"):
            return stripped.split(":", 1)[1].strip().strip("'\"")
        if stripped.startswith("# "):
            return stripped[2:].strip()
        if stripped.lower().startswith("<title>"):
            return re.sub(r"</?title>", "", stripped, flags=re.I).strip()
    return fallback


def read_org_date(path: Path) -> str | None:
    for line in read_text(path).splitlines()[:20]:
        if line.strip().lower().startswith("#+date:"):
            return line.split(":", 1)[1].strip()
    return None


def extract_url(path: Path) -> str | None:
    for line in read_text(path).splitlines()[:30]:
        stripped = line.strip()
        if stripped.startswith("url:"):
            return stripped.split(":", 1)[1].strip().strip('"')
        match = re.search(r"https?://\S+", stripped)
        if match:
            return match.group(0).rstrip(")")
    return None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the Investment Intelligence Hub parallel pipeline.")
    parser.add_argument("--date", required=True)
    parser.add_argument("--mode", default="parallel")
    parser.add_argument("--daily-report")
    parser.add_argument("--ljg-report")
    parser.add_argument("--x-md")
    parser.add_argument("--x-posts-dir")
    parser.add_argument("--export-html", action="store_true")
    parser.add_argument("--skip-migration-log", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def previous_day_parts(date: str) -> tuple[str, str]:
    prior = datetime.strptime(date, "%Y-%m-%d").date() - timedelta(days=1)
    return prior.strftime("%Y_%m_%d"), prior.strftime("%Y%m%d")


def collect_x_files(args: argparse.Namespace) -> tuple[list[tuple[Path, str]], list[str]]:
    warnings: list[str] = []
    files: list[tuple[Path, str]] = []
    if args.x_posts_dir:
        x_dir = as_path(args.x_posts_dir)
        if not x_dir or not x_dir.exists():
            warnings.append(f"--x-posts-dir missing: {rel(x_dir) if x_dir else args.x_posts_dir}")
            return files, warnings
        candidates = sorted(path for path in x_dir.iterdir() if path.is_file() and path.suffix.lower() in {".md", ".html"})
        if not candidates:
            warnings.append(f"--x-posts-dir has no .md/.html files: {rel(x_dir)}")
            return files, warnings
        if len(candidates) > X_FILE_LIMIT:
            warnings.append(f"--x-posts-dir has {len(candidates)} X files; included first {X_FILE_LIMIT} sorted files.")
            candidates = candidates[:X_FILE_LIMIT]
        return [(path, "x_post") for path in candidates], warnings

    if args.x_md:
        x_file = as_path(args.x_md)
        if not x_file or not x_file.exists():
            warnings.append(f"--x-md missing: {rel(x_file) if x_file else args.x_md}")
            return files, warnings
        source_type = "x_html" if x_file.suffix.lower() == ".html" else "x_markdown"
        return [(x_file, source_type)], warnings

    folder_name, prefix = previous_day_parts(args.date)
    default_dir = X_POSTS_ROOT / folder_name
    if not default_dir.exists():
        warnings.append(f"default previous-day x_posts folder missing: {rel(default_dir)}")
        return files, warnings
    all_candidates = sorted(path for path in default_dir.iterdir() if path.is_file() and path.suffix.lower() in {".md", ".html"})
    preferred = [path for path in all_candidates if path.name.startswith(f"{prefix}_")]
    candidates = preferred or all_candidates
    if not candidates:
        warnings.append(f"default previous-day x_posts folder has no .md/.html files: {rel(default_dir)}")
        return files, warnings
    if not preferred:
        warnings.append(f"default previous-day x_posts folder had no {prefix}_*.md/html files; included sorted .md/.html files instead.")
    if len(candidates) > X_FILE_LIMIT:
        warnings.append(f"default previous-day x_posts folder has {len(candidates)} X files; included first {X_FILE_LIMIT} sorted files.")
        candidates = candidates[:X_FILE_LIMIT]
    return [(path, "x_post") for path in candidates], warnings


def resolve_inputs(args: argparse.Namespace) -> tuple[Path, Path | None, list[tuple[Path, str]], list[str]]:
    daily = as_path(args.daily_report) or ROOT / f"reports/daily/{args.date}.md"
    ljg = as_path(args.ljg_report)
    missing_optional: list[str] = []
    if ljg is None:
        missing_optional.append("--ljg-report not provided")
    elif not ljg.exists():
        missing_optional.append(f"--ljg-report missing: {rel(ljg)}")
        ljg = None
    x_files, x_warnings = collect_x_files(args)
    missing_optional.extend(x_warnings)
    return daily, ljg, x_files, missing_optional


def output_paths(date: str, export_html: bool = False) -> dict[str, Path]:
    paths = {
        "sources": HUB / f"processed/sources/{date}.jsonl",
        "signals": HUB / f"processed/signals/{date}.jsonl",
        "ticker_impacts": HUB / f"processed/ticker_impacts/{date}.jsonl",
        "thesis_impacts": HUB / f"processed/thesis_impacts/{date}.jsonl",
        "brief": HUB / f"reports/daily_intelligence/{date}.md",
        "notes": HUB / f"reports/daily_intelligence/{date}_notes.md",
        "validation": HUB / f"reports/daily_intelligence/{date}_validation.md",
    }
    if export_html:
        paths["html"] = HUB / f"reports/daily_intelligence/html/{date}.html"
        paths["html_notes"] = HUB / f"reports/daily_intelligence/{date}_html_notes.md"
    return paths


def source_records(date: str, ingested_at: str, daily: Path, ljg: Path | None, x_files: list[tuple[Path, str]]) -> list[dict]:
    if not daily.exists():
        raise FileNotFoundError(f"Daily report is required and was not found: {rel(daily)}")
    inputs = [
        {
            "source_id": stable_source_id(date, "daily_report", daily),
            "source_type": "daily_report",
            "title": read_title(daily, f"AI 投资新闻日报 - {date}"),
            "author_or_origin": "ai-investing-monitor",
            "url": f"docs/reports/{date}.html",
            "local_path": rel(daily),
            "published_at": date,
            "provenance_notes": "Registered by the parallel hub pipeline. Original daily report was not copied, moved, or rewritten.",
        }
    ]
    if ljg is not None:
        inputs.append(
            {
                "source_id": stable_source_id(date, "ljg_invest_report", ljg),
                "source_type": "ljg_invest_report",
                "title": read_title(ljg, ljg.stem),
                "author_or_origin": "ljg-invest report",
                "url": None,
                "local_path": rel(ljg),
                "published_at": read_org_date(ljg),
                "provenance_notes": "Registered by the parallel hub pipeline. Original org-mode report was not copied, moved, or rewritten.",
            }
        )
    for x_path, source_type in x_files:
        inputs.append(
            {
                "source_id": stable_source_id(date, source_type, x_path),
                "source_type": source_type,
                "title": read_title(x_path, x_path.stem),
                "author_or_origin": "User-captured X source",
                "url": extract_url(x_path),
                "local_path": rel(x_path),
                "published_at": None,
                "provenance_notes": "Registered by the parallel hub pipeline. Original X converted or captured file was not copied, moved, or rewritten.",
            }
        )
    rows = []
    for item in inputs:
        path = ROOT / item["local_path"]
        rows.append(
            {
                **item,
                "ingested_at": ingested_at,
                "source_quality": SOURCE_QUALITY[item["source_type"]],
                "content_hash": sha256(path),
                "status": "registered",
            }
        )
    return rows


def source_id_by_type(sources: list[dict], source_type: str) -> str | None:
    for row in sources:
        if row["source_type"] == source_type:
            return row["source_id"]
    return None


def source_ids_by_types(sources: list[dict], source_types: set[str]) -> list[str]:
    return [row["source_id"] for row in sources if row["source_type"] in source_types]


def source_type_string(source_ids: list[str], source_by_id: dict[str, dict]) -> str:
    return ",".join(source_by_id[sid]["source_type"] for sid in source_ids)


def quality_for_sources(source_ids: list[str], source_by_id: dict[str, dict]) -> float:
    values = [source_by_id[sid]["source_quality"]["score"] for sid in source_ids]
    return round(sum(values) / len(values), 2)


def extract_known_tickers(path: Path) -> list[str]:
    text = read_text(path)
    found = sorted(ticker for ticker in KNOWN_TICKERS if re.search(rf"\b{re.escape(ticker)}\b", text))
    return found


def signal_rows(date: str, sources: list[dict]) -> list[dict]:
    source_by_id = {row["source_id"]: row for row in sources}
    daily = source_id_by_type(sources, "daily_report")
    ljg = source_id_by_type(sources, "ljg_invest_report")
    x_sources = [row for row in sources if row["source_type"] in {"x_post", "x_markdown", "x_html"}]
    rows = [
        {
            "signal_id": f"sig_{date}_daily_networking",
            "date": date,
            "claim": "The daily report ranks Networking as a high-importance AI infrastructure chokepoint and lists NOK among related stocks.",
            "evidence_summary": "The dated daily report ranks Networking at 80 with related stocks ANET, AVGO, MRVL, CSCO, and NOK.",
            "source_ids": [daily],
            "tickers": ["ANET", "AVGO", "MRVL", "CSCO", "NOK"],
            "themes": ["Networking", "AI Infrastructure"],
            "direction": "neutral",
            "time_horizon": "short",
            "confidence": 0.58,
            "source_quality_score": 0.65,
            "evidence_strength_score": 0.55,
            "thesis_relevance_score": 0.70,
            "market_impact_score": 0.55,
            "noise_risk_score": 0.35,
            "verification_needed": True,
            "status": "watch_only",
        },
        {
            "signal_id": f"sig_{date}_daily_optical",
            "date": date,
            "claim": "The daily report treats Optical Interconnect as a medium-stable chokepoint and includes NOK in the related-stock set.",
            "evidence_summary": "The Optical Interconnect section lists AAOI, COHR, CIEN, LITE, NOK, CRDO, ALAB, MRVL, and AVGO as related stocks.",
            "source_ids": [daily],
            "tickers": ["AAOI", "COHR", "CIEN", "LITE", "NOK", "CRDO", "ALAB", "MRVL", "AVGO"],
            "themes": ["Optical Interconnect", "AI Infrastructure"],
            "direction": "neutral",
            "time_horizon": "short",
            "confidence": 0.57,
            "source_quality_score": 0.65,
            "evidence_strength_score": 0.55,
            "thesis_relevance_score": 0.72,
            "market_impact_score": 0.52,
            "noise_risk_score": 0.35,
            "verification_needed": True,
            "status": "watch_only",
        },
        {
            "signal_id": f"sig_{date}_daily_mrvl_price_volume",
            "date": date,
            "claim": "MRVL showed a large daily move and volume flag in the daily report while a mainstream-news catalyst was also present.",
            "evidence_summary": "The daily report cites Marvell Technology joining the S&P 500 index and flags MRVL with a daily move greater than 5 percent plus volume above 2x its 20-day average.",
            "source_ids": [daily],
            "tickers": ["MRVL"],
            "themes": ["ASIC / Custom Silicon", "Networking", "Optical Interconnect"],
            "direction": "mixed",
            "time_horizon": "short",
            "confidence": 0.60,
            "source_quality_score": 0.65,
            "evidence_strength_score": 0.68,
            "thesis_relevance_score": 0.62,
            "market_impact_score": 0.70,
            "noise_risk_score": 0.30,
            "verification_needed": True,
            "status": "watch_only",
        },
        {
            "signal_id": f"sig_{date}_daily_high_risk_concepts",
            "date": date,
            "claim": "The daily report found no major company news, earnings, orders, or regulatory filings for the high-risk concept group.",
            "evidence_summary": "The high-risk concept section states that POET, LWLG, SIVE, and FOCI had no major news, earnings, orders, or regulatory filings on the report date.",
            "source_ids": [daily],
            "tickers": ["POET", "LWLG", "SIVE", "FOCI"],
            "themes": ["High-risk concepts", "AI Infrastructure"],
            "direction": "neutral",
            "time_horizon": "short",
            "confidence": 0.55,
            "source_quality_score": 0.65,
            "evidence_strength_score": 0.50,
            "thesis_relevance_score": 0.45,
            "market_impact_score": 0.35,
            "noise_risk_score": 0.40,
            "verification_needed": True,
            "status": "watch_only",
        },
    ]
    if ljg:
        rows.extend(
            [
                {
                    "signal_id": f"sig_{date}_ljg_nok_network_flywheel",
                    "date": "2026-06-02",
                    "claim": "The NOK research note argues that Nokia's Network Infrastructure flywheel has started while Mobile Infrastructure AI-RAN has not yet reached cash-flow validation.",
                    "evidence_summary": "The note separates Nokia into a Network Infrastructure flywheel supported by AI and cloud network demand, and a Mobile Infrastructure AI-RAN layer that remains an option requiring commercial proof.",
                    "source_ids": [ljg],
                    "tickers": ["NOK"],
                    "themes": ["Networking", "Optical Networks", "AI-RAN", "6G"],
                    "direction": "mixed",
                    "time_horizon": "medium",
                    "confidence": 0.62,
                    "source_quality_score": 0.70,
                    "evidence_strength_score": 0.58,
                    "thesis_relevance_score": 0.85,
                    "market_impact_score": 0.66,
                    "noise_risk_score": 0.32,
                    "verification_needed": True,
                    "status": "needs_corroboration",
                },
                {
                    "signal_id": f"sig_{date}_ljg_nok_q1_ai_cloud",
                    "date": "2026-06-02",
                    "claim": "The NOK research note cites Q1 2026 AI and Cloud growth, AI and Cloud orders, Optical Networks growth, and raised Network Infrastructure guidance as evidence of demand traction.",
                    "evidence_summary": "The note reports Q1 2026 AI and Cloud net sales growth of 49 percent, about 1 billion euros of new AI and Cloud orders, Optical Networks growth of 20 percent, and Network Infrastructure guidance raised to 12 to 14 percent growth.",
                    "source_ids": [ljg],
                    "tickers": ["NOK"],
                    "themes": ["AI and Cloud", "Optical Networks", "Network Infrastructure"],
                    "direction": "constructive",
                    "time_horizon": "medium",
                    "confidence": 0.64,
                    "source_quality_score": 0.70,
                    "evidence_strength_score": 0.66,
                    "thesis_relevance_score": 0.88,
                    "market_impact_score": 0.70,
                    "noise_risk_score": 0.25,
                    "verification_needed": True,
                    "status": "needs_corroboration",
                },
                {
                    "signal_id": f"sig_{date}_ljg_nok_ai_ran_uncertain",
                    "date": "2026-06-02",
                    "claim": "The NOK research note frames AI-RAN and 6G as a future option that still needs commercial deployment and operator business-model validation.",
                    "evidence_summary": "The note says AI-RAN is not current cash flow and still needs proof across deployment, standards, power use, total ownership cost, and application demand.",
                    "source_ids": [ljg],
                    "tickers": ["NOK"],
                    "themes": ["AI-RAN", "6G", "Mobile Infrastructure"],
                    "direction": "mixed",
                    "time_horizon": "long",
                    "confidence": 0.60,
                    "source_quality_score": 0.70,
                    "evidence_strength_score": 0.55,
                    "thesis_relevance_score": 0.82,
                    "market_impact_score": 0.60,
                    "noise_risk_score": 0.38,
                    "verification_needed": True,
                    "status": "needs_corroboration",
                },
            ]
        )
    for idx, source in enumerate(x_sources[:3], 1):
        path = ROOT / source["local_path"]
        tickers = extract_known_tickers(path)
        ticker_phrase = f" involving {', '.join(tickers)}" if tickers else ""
        rows.append(
            {
                "signal_id": f"sig_{date}_x_{idx:02d}_unverified_narrative",
                "date": date,
                "claim": f"A user-captured X source raises an unverified market narrative{ticker_phrase} that requires corroboration before thesis use.",
                "evidence_summary": f"The source `{source['local_path']}` is a Tier 4 X input. It is registered for discovery only and needs confirmation from higher-quality sources.",
                "source_ids": [source["source_id"]],
                "tickers": tickers,
                "themes": ["X Narrative", "Market Discovery"],
                "direction": "unknown",
                "time_horizon": "unknown",
                "confidence": 0.45,
                "source_quality_score": quality_for_sources([source["source_id"]], source_by_id),
                "evidence_strength_score": 0.35,
                "thesis_relevance_score": 0.50 if tickers else 0.35,
                "market_impact_score": 0.40,
                "noise_risk_score": 0.62,
                "verification_needed": True,
                "status": "needs_corroboration",
            }
        )
    for row in rows:
        row["source_type"] = source_type_string(row["source_ids"], source_by_id)
    return rows


def has_signal(signals: list[dict], signal_id: str) -> bool:
    return any(row["signal_id"] == signal_id for row in signals)


def ticker_impacts(date: str, signals: list[dict]) -> list[dict]:
    rows = []
    nok_ids = [sid for sid in [
        f"sig_{date}_daily_networking",
        f"sig_{date}_daily_optical",
        f"sig_{date}_ljg_nok_network_flywheel",
        f"sig_{date}_ljg_nok_q1_ai_cloud",
        f"sig_{date}_ljg_nok_ai_ran_uncertain",
        *[row["signal_id"] for row in signals if "NOK" in row.get("tickers", []) and row["source_type"].startswith("x_")],
    ] if has_signal(signals, sid)]
    if nok_ids:
        rows.append(
            {
                "ticker": "NOK",
                "date": date,
                "signal_ids": nok_ids,
                "watchlist_group": "key_observation",
                "thesis_impact": "supports_speculation_thesis" if len(nok_ids) > 2 else "insufficient_evidence",
                "impact_summary": "NOK has dated-source relevance to networking, optical transport, AI and Cloud demand, AI-RAN optionality, or X narrative discovery, but the evidence remains mixed and needs verification.",
                "risk_flags": ["needs_primary_source_verification", "generated_daily_report_not_primary_proof"],
                "research_label": "thesis_review" if len(nok_ids) > 2 else "verify",
                "follow_up_questions": [
                    "Which Nokia company filings or investor materials confirm the AI and Cloud and Optical Networks claims?",
                    "What evidence shows AI-RAN moving from trials toward commercial deployments?",
                ],
            }
        )
    if has_signal(signals, f"sig_{date}_daily_mrvl_price_volume"):
        rows.append(
            {
                "ticker": "MRVL",
                "date": date,
                "signal_ids": [sid for sid in [f"sig_{date}_daily_networking", f"sig_{date}_daily_optical", f"sig_{date}_daily_mrvl_price_volume"] if has_signal(signals, sid)],
                "watchlist_group": "core_holdings_planned",
                "thesis_impact": "insufficient_evidence",
                "impact_summary": "MRVL appears in the daily report as a related networking and optical ticker and has a price-volume flag tied to an index-related news item, but this does not establish a durable business-thesis change.",
                "risk_flags": ["price_volume_flag", "daily_report_generated_context", "event_may_not_be_business_fundamental"],
                "research_label": "risk_review",
                "follow_up_questions": ["Is the index-related news relevant to business fundamentals or mainly market-structure flow?"],
            }
        )
    for ticker, sid, group, summary in [
        ("ANET", f"sig_{date}_daily_networking", "core_holdings_planned", "ANET is listed in the daily report's Networking chokepoint set, but the dated signal does not include company-specific evidence beyond generated category relevance."),
        ("AAOI", f"sig_{date}_daily_optical", "core_holdings_planned", "AAOI is listed in the daily report's Optical Interconnect related-stock set, but the signal is category-level and lacks direct company evidence."),
        ("POET", f"sig_{date}_daily_high_risk_concepts", "high_risk_concepts", "POET appears in the daily report's high-risk concept group where no major news, earnings, orders, or regulatory filings were found on the dated run."),
    ]:
        if has_signal(signals, sid):
            rows.append(
                {
                    "ticker": ticker,
                    "date": date,
                    "signal_ids": [sid],
                    "watchlist_group": group,
                    "thesis_impact": "no_material_impact",
                    "impact_summary": summary,
                    "risk_flags": ["daily_report_generated_context"] if ticker != "POET" else ["absence_of_news_only", "high_risk_concept_group"],
                    "research_label": "weekly_review_candidate" if ticker == "POET" else "monitor",
                    "follow_up_questions": ["Check primary-source updates before carrying this signal forward."],
                }
            )
    for signal in signals:
        if signal["source_type"].startswith("x_"):
            for ticker in signal.get("tickers", []):
                if ticker not in {row["ticker"] for row in rows}:
                    rows.append(
                        {
                            "ticker": ticker,
                            "date": date,
                            "signal_ids": [signal["signal_id"]],
                            "watchlist_group": "x_discovery",
                            "thesis_impact": "insufficient_evidence",
                            "impact_summary": "Ticker appeared in a Tier 4 X discovery source only and needs corroboration before thesis use.",
                            "risk_flags": ["x_only", "needs_corroboration"],
                            "research_label": "verify",
                            "follow_up_questions": ["Find higher-quality confirmation before using this signal outside discovery tracking."],
                        }
                    )
    return rows[:12]


def thesis_impacts(date: str, signals: list[dict]) -> list[dict]:
    rows = []
    nok_network_ids = [sid for sid in [
        f"sig_{date}_daily_networking",
        f"sig_{date}_daily_optical",
        f"sig_{date}_ljg_nok_network_flywheel",
        f"sig_{date}_ljg_nok_q1_ai_cloud",
        *[row["signal_id"] for row in signals if "NOK" in row.get("tickers", []) and row["source_type"].startswith("x_")],
    ] if has_signal(signals, sid)]
    if nok_network_ids:
        rows.append(
            {
                "thesis_impact_id": f"thesis_{date}_nok_ai_networking",
                "date": date,
                "ticker_or_theme": "NOK / AI networking and optical transport",
                "signal_ids": nok_network_ids,
                "current_thesis_type": "speculation_thesis",
                "impact_direction": "strengthens" if len(nok_network_ids) > 2 else "unclear",
                "evidence_quality": "medium" if len(nok_network_ids) > 2 else "low",
                "confidence": 0.56 if len(nok_network_ids) > 2 else 0.42,
                "rationale": "Dated sources point toward NOK relevance in AI networking and optical transport, but the strongest details still need source verification and any X element is discovery-only.",
                "required_verification": ["Confirm NOK AI and Cloud and Optical Networks claims from company materials."],
                "proposed_memory_update": None,
            }
        )
    if has_signal(signals, f"sig_{date}_ljg_nok_ai_ran_uncertain"):
        rows.append(
            {
                "thesis_impact_id": f"thesis_{date}_nok_ai_ran",
                "date": date,
                "ticker_or_theme": "NOK / AI-RAN and 6G",
                "signal_ids": [f"sig_{date}_ljg_nok_ai_ran_uncertain"],
                "current_thesis_type": "watch_only",
                "impact_direction": "unclear",
                "evidence_quality": "medium",
                "confidence": 0.48,
                "rationale": "The research note treats AI-RAN and 6G as future optionality rather than validated current cash flow, so this remains watch-only pending commercial evidence.",
                "required_verification": ["Look for operator deployments, revenue model evidence, and company disclosures tied to AI-RAN or 6G commercialization."],
                "proposed_memory_update": None,
            }
        )
    for impact_id, theme, sid, quality, conf, rationale in [
        ("mrvl_event", "MRVL / index-related event and market movement", f"sig_{date}_daily_mrvl_price_volume", "medium", 0.46, "The MRVL signal combines a mainstream-news index event with price and volume flags, but does not establish a direct business-fundamental thesis change."),
        ("optical_theme", "Optical Interconnect theme", f"sig_{date}_daily_optical", "low", 0.42, "The optical theme appears in a generated daily-report chokepoint ranking, which is useful for monitoring but not primary-source support for a durable thesis."),
        ("high_risk_concepts", "High-risk concept group", f"sig_{date}_daily_high_risk_concepts", "low", 0.40, "The signal records absence of major news for high-risk concept tickers; it is useful for review tracking but does not alter a durable thesis."),
    ]:
        if has_signal(signals, sid):
            rows.append(
                {
                    "thesis_impact_id": f"thesis_{date}_{impact_id}",
                    "date": date,
                    "ticker_or_theme": theme,
                    "signal_ids": [sid],
                    "current_thesis_type": "watch_only" if impact_id != "mrvl_event" else "unknown",
                    "impact_direction": "neutral" if impact_id != "mrvl_event" else "unclear",
                    "evidence_quality": quality,
                    "confidence": conf,
                    "rationale": rationale,
                    "required_verification": ["Check primary-source evidence before using this in durable memory."],
                    "proposed_memory_update": None,
                }
            )
    x_ids = [row["signal_id"] for row in signals if row["source_type"].startswith("x_")]
    if x_ids:
        rows.append(
            {
                "thesis_impact_id": f"thesis_{date}_x_discovery",
                "date": date,
                "ticker_or_theme": "X discovery narratives",
                "signal_ids": x_ids,
                "current_thesis_type": "speculation_thesis",
                "impact_direction": "unclear",
                "evidence_quality": "low",
                "confidence": 0.35,
                "rationale": "X sources are discovery inputs only and cannot support durable thesis updates alone.",
                "required_verification": ["Corroborate any X-only narrative with daily/core financial news or primary sources."],
                "proposed_memory_update": None,
            }
        )
    return rows


def label_for_signal(signal: dict, ticker_rows: list[dict]) -> str:
    for row in ticker_rows:
        if signal["signal_id"] in row["signal_ids"]:
            return row["research_label"]
    return "verify" if signal["status"] == "needs_corroboration" else "monitor"


def brief(date: str, sources: list[dict], signals: list[dict], ticker_rows: list[dict], thesis_rows: list[dict]) -> str:
    strongest = max(signals, key=lambda row: row["evidence_strength_score"])
    noisiest = max(signals, key=lambda row: row["noise_risk_score"])
    lines = [
        f"# Investment Intelligence Brief - {date}",
        "",
        "Research-only. No trading automation. No buy/sell instructions. Action labels are research workflow labels only.",
        "",
        "## 1. Executive Summary",
        "",
        f"- What changed across sources: This parallel run registered {len(sources)} source(s) and extracted {len(signals)} research signal(s).",
        f"- Strongest source-backed signal: `{strongest['signal_id']}` has the highest evidence-strength score in this run.",
        f"- Weakest / noisiest signal: `{noisiest['signal_id']}` has the highest noise-risk score and needs careful treatment.",
        "- Main thesis implication: Any thesis impact remains research-only and non-canonical pending verification.",
        "- Main verification task: Check company or primary-source materials before updating durable memory.",
        "",
        "## 2. Cross-Source Signal Table",
        "",
        "| Rank | Signal | Tickers / Themes | Source Type | Source Quality | Evidence Strength | Noise Risk | Research Label |",
        "|---:|---|---|---|---:|---:|---:|---|",
    ]
    ranked = sorted(signals, key=lambda row: (row["evidence_strength_score"], -row["noise_risk_score"]), reverse=True)
    for idx, row in enumerate(ranked, 1):
        tickers = ", ".join(row["tickers"]) or "No explicit ticker"
        lines.append(
            f"| {idx} | `{row['signal_id']}`: {row['claim']} | {tickers} / {', '.join(row['themes'])} | "
            f"{row['source_type']} | {row['source_quality_score']:.2f} | {row['evidence_strength_score']:.2f} | {row['noise_risk_score']:.2f} | {label_for_signal(row, ticker_rows)} |"
        )
    lines.extend(["", "## 3. Thesis Impact Map", "", "| Ticker / Theme | Current Thesis Type | Impact Direction | Evidence Quality | Confidence | Rationale | Required Verification |", "|---|---|---|---|---:|---|---|"])
    for row in thesis_rows:
        lines.append(
            f"| {row['ticker_or_theme']} | {row['current_thesis_type']} | {row['impact_direction']} | {row['evidence_quality']} | {row['confidence']:.2f} | "
            f"{row['rationale']} | {'; '.join(row['required_verification'])} |"
        )
    lines.extend(
        [
            "",
            "## 4. Watchlist Impact",
            "",
            "Portfolio holdings are unconfirmed in `memory/portfolio_context.md`, so this section is treated as watchlist impact only.",
            "",
            "| Watchlist Group | Ticker | Thesis Impact | Impact Summary | Risk Flags | Research Label | Follow-Up |",
            "|---|---|---|---|---|---|---|",
        ]
    )
    for row in ticker_rows:
        lines.append(
            f"| {row['watchlist_group']} | {row['ticker']} | {row['thesis_impact']} | {row['impact_summary']} | "
            f"{'; '.join(row['risk_flags'])} | {row['research_label']} | {'; '.join(row['follow_up_questions'])} |"
        )
    noise_rows = [
        (f"`sig_{date}_daily_optical`", "daily_report", "Generated category relevance, not primary-source proof.", "Company filings, earnings commentary, or industry data supporting optical demand by ticker."),
        (f"`sig_{date}_daily_high_risk_concepts`", "daily_report", "Useful tracker, but low thesis relevance and based on lack of detected items.", "Later primary-source update or verified material event."),
    ]
    x_signal_ids = [row["signal_id"] for row in signals if row["source_type"].startswith("x_")]
    for signal_id in x_signal_ids:
        noise_rows.insert(0, (f"`{signal_id}`", "x_post", "Tier 4 X-only discovery item; unverified unless corroborated by higher-quality sources.", "Company, customer, core financial news, or high-quality industry confirmation."))
    lines.extend(["", "## 5. Noise / Hype Filter", "", "| Item | Source | Why It Is Noise / Unverified | What Would Upgrade It |", "|---|---|---|---|"])
    for item, source, why, upgrade in noise_rows:
        lines.append(f"| {item} | {source} | {why} | {upgrade} |")
    labels: dict[str, list[str]] = {}
    for row in ticker_rows:
        labels.setdefault(row["research_label"], []).append(row["ticker"])
    lines.extend(["", "## 6. Action Labels", "", "| Research Label | Records | Meaning In This Run |", "|---|---|---|"])
    for label in ["verify", "monitor", "thesis_review", "risk_review", "ignore_noise", "weekly_review_candidate"]:
        records = ", ".join(labels.get(label, [])) or "None assigned"
        meaning = {
            "verify": "Needs corroboration before durable use.",
            "monitor": "Useful watchlist context without durable thesis impact.",
            "thesis_review": "Could affect thesis framing after primary-source checks.",
            "risk_review": "Needs separation of market/event context from business evidence.",
            "ignore_noise": "Candidate items are tracked in the noise filter instead.",
            "weekly_review_candidate": "Non-urgent review tracker.",
        }[label]
        lines.append(f"| {label} | {records} | {meaning} |")
    lines.extend(
        [
            "",
            "## 7. Follow-Up Checklist",
            "",
            "- [ ] Source verification: Confirm the highest-impact claims from company or primary-source materials.",
            "- [ ] Company / primary-source check: Review any NOK AI networking, Optical Networks, AI-RAN, or 6G claims before durable memory use.",
            "- [ ] Company / primary-source check: Review MRVL company updates to separate event-driven market movement from business evidence.",
            "- [ ] Thesis memory proposal candidate: Prepare only a human-reviewed proposal if verification supports it.",
            "- [ ] Weekly review candidate: Track high-risk concept absence-of-news signals only if the pattern persists.",
            "",
        ]
    )
    return "\n".join(lines)


def notes(date: str, inputs: list[str], missing_optional: list[str], outputs: list[str], counts: dict[str, int], command: str) -> str:
    return "\n".join(
        [
            f"# Daily Intelligence Brief Notes - {date}",
            "",
            f"Timestamp: {datetime.now(TZ).strftime('%Y-%m-%dT%H:%M:%S%z')}",
            "",
            "## Command",
            "",
            f"`{command}`",
            "",
            "## Input Files Used",
            "",
            *[f"- `{item}`" for item in inputs],
            "",
            "## Missing Optional Inputs / Warnings",
            "",
            *([f"- {item}" for item in missing_optional] or ["- None"]),
            "",
            "## Output Files Created",
            "",
            *[f"- `{item}`" for item in outputs],
            "",
            "## Summary Counts",
            "",
            f"- Sources: {counts['sources']}",
            f"- Signals: {counts['signals']}",
            f"- Ticker impacts: {counts['ticker_impacts']}",
            f"- Thesis impacts: {counts['thesis_impacts']}",
            "",
            "## Boundary Confirmation",
            "",
            "- Holdings were treated as unconfirmed; the brief uses Watchlist Impact.",
            "- No durable memory thesis files were updated.",
            "- No production scripts were modified.",
            "- Existing ai-investing-monitor report generation logic was not changed.",
            "- Existing report files, ljg-invest files, and X converted files were not moved or rewritten.",
            "- No trading automation was created.",
            "- No trade instructions were generated.",
            "",
        ]
    )


def validate_data(date: str, sources: list[dict], signals: list[dict], ticker_rows: list[dict], thesis_rows: list[dict], brief_text: str) -> list[str]:
    checks: list[str] = []
    source_ids = {row["source_id"] for row in sources}
    signal_ids = {row["signal_id"] for row in signals}
    assert 3 <= len(signals) <= 12
    checks.append("Signal count is between 3 and 12.")
    assert all(set(row["source_ids"]) <= source_ids for row in signals)
    checks.append("All signal source_ids exist in source records.")
    assert all("source_type" in row and row["source_type"] for row in signals)
    checks.append("Every signal includes source_type.")
    assert all(set(row["signal_ids"]) <= signal_ids for row in ticker_rows)
    checks.append("All ticker impact signal_ids exist in signals.")
    assert all(set(row["signal_ids"]) <= signal_ids for row in thesis_rows)
    checks.append("All thesis impact signal_ids exist in signals.")
    for row in signals:
        for field in ["confidence", "source_quality_score", "evidence_strength_score", "thesis_relevance_score", "market_impact_score", "noise_risk_score"]:
            value = row[field]
            assert isinstance(value, (int, float)) and 0 <= value <= 1
        source_types = {source["source_type"] for source in sources if source["source_id"] in row["source_ids"]}
        if source_types <= {"x_post", "x_markdown", "x_html"}:
            assert row["status"] == "needs_corroboration" and row["verification_needed"] is True
    for row in thesis_rows:
        assert isinstance(row["confidence"], (int, float)) and 0 <= row["confidence"] <= 1
    checks.append("All score and confidence fields are numeric between 0 and 1.")
    checks.append("Tier 4 X-only signals are marked needs_corroboration.")
    sections = [
        f"# Investment Intelligence Brief - {date}",
        "## 1. Executive Summary",
        "## 2. Cross-Source Signal Table",
        "## 3. Thesis Impact Map",
        "## 4. Watchlist Impact",
        "## 5. Noise / Hype Filter",
        "## 6. Action Labels",
        "## 7. Follow-Up Checklist",
    ]
    assert all(section in brief_text for section in sections)
    assert "Holdings Impact" not in brief_text
    checks.append("Brief contains all 7 sections and uses Watchlist Impact.")
    bad = []
    for line_no, line in enumerate(brief_text.splitlines(), start=1):
        if line_no <= 3:
            continue
        if FORBIDDEN.search(line):
            bad.append((line_no, line))
    assert not bad, f"Forbidden terms outside disclaimer: {bad}"
    checks.append("Forbidden trading instruction words appear only in the opening disclaimer context.")
    return checks


def validation_markdown(date: str, command: str, inputs: list[str], missing_optional: list[str], outputs: list[str], counts: dict[str, int], checks: list[str]) -> str:
    return "\n".join(
        [
            f"# Hub Pipeline Validation - {date}",
            "",
            f"Timestamp: {datetime.now(TZ).strftime('%Y-%m-%dT%H:%M:%S%z')}",
            "",
            "## Command Run",
            "",
            f"`{command}`",
            "",
            "## Input Files Used",
            "",
            *[f"- `{item}`" for item in inputs],
            "",
            "## Missing Optional Inputs / Warnings",
            "",
            *([f"- {item}" for item in missing_optional] or ["- None"]),
            "",
            "## Output Files Created",
            "",
            *[f"- `{item}`" for item in outputs],
            "",
            "## Counts",
            "",
            f"- Source count: {counts['sources']}",
            f"- Signal count: {counts['signals']}",
            f"- Ticker impact count: {counts['ticker_impacts']}",
            f"- Thesis impact count: {counts['thesis_impacts']}",
            "",
            "## Validation Checks",
            "",
            *[f"- {check}" for check in checks],
            "",
            "## Boundary Confirmation",
            "",
            "- Existing production scripts were not modified.",
            "- Existing ai-investing-monitor report generation logic was not changed.",
            "- Existing watchlist, theme, daily report, ljg-invest, and X converted files were not moved or rewritten.",
            "- The hub was not made canonical and was not linked from docs/index.html.",
            "- Durable memory thesis files were not updated.",
            "- Primary Source registry is deferred to Phase 8 and was not created.",
            "- No trading automation was created.",
            "- No trade instructions were generated.",
            "",
        ]
    )


def markdown_to_html(markdown: str, title: str) -> str:
    body: list[str] = []
    in_table = False
    for line in markdown.splitlines():
        if line.startswith("|") and line.endswith("|"):
            cells = [html.escape(cell.strip()) for cell in line.strip("|").split("|")]
            if set(cells[0].replace("-", "").replace(":", "")) == set() if cells else False:
                continue
            if not in_table:
                body.append("<table>")
                in_table = True
            tag = "th" if cells and cells[0] in {"Rank", "Ticker / Theme", "Watchlist Group", "Item", "Research Label"} else "td"
            body.append("<tr>" + "".join(f"<{tag}>{cell}</{tag}>" for cell in cells) + "</tr>")
            continue
        if in_table:
            body.append("</table>")
            in_table = False
        if line.startswith("# "):
            body.append(f"<h1>{html.escape(line[2:].strip())}</h1>")
        elif line.startswith("## "):
            body.append(f"<h2>{html.escape(line[3:].strip())}</h2>")
        elif line.startswith("- [ ] "):
            body.append(f"<p class=\"check\">□ {html.escape(line[6:].strip())}</p>")
        elif line.startswith("- "):
            body.append(f"<p class=\"bullet\">{html.escape(line[2:].strip())}</p>")
        elif line.strip():
            body.append(f"<p>{html.escape(line.strip())}</p>")
    if in_table:
        body.append("</table>")
    return "\n".join(
        [
            "<!doctype html>",
            "<html lang=\"en\">",
            "<head>",
            "<meta charset=\"utf-8\">",
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
            f"<title>{html.escape(title)}</title>",
            "<style>",
            "body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;line-height:1.5;color:#1f2933;max-width:1180px;margin:0 auto;padding:32px 20px;background:#f7f8fa}",
            "main{background:#fff;border:1px solid #d8dee4;border-radius:8px;padding:28px}",
            "h1{font-size:30px;margin:0 0 16px}h2{font-size:20px;margin-top:30px;border-top:1px solid #e5e7eb;padding-top:18px}",
            "table{width:100%;border-collapse:collapse;margin:12px 0 20px;font-size:14px}th,td{border:1px solid #d8dee4;padding:8px;vertical-align:top}th{background:#eef2f6;text-align:left}",
            ".disclaimer{font-weight:600;color:#5b6472}.bullet:before{content:'• ';}.check{margin-left:4px}",
            "</style>",
            "</head>",
            "<body><main>",
            "<p class=\"disclaimer\">Research-only. No trading automation. No buy/sell instructions. Watchlist labels are not confirmed holdings.</p>",
            *body,
            "</main></body></html>",
        ]
    )


def publish_safe_warnings(text: str) -> list[str]:
    warnings = []
    for label, pattern in SENSITIVE_PATTERNS:
        if pattern.search(text):
            warnings.append(f"Detected possible {label}.")
    return warnings


def html_notes(date: str, input_md: str, output_html: str, warnings: list[str]) -> str:
    return "\n".join(
        [
            f"# HTML Export Notes - {date}",
            "",
            f"Timestamp: {datetime.now(TZ).strftime('%Y-%m-%dT%H:%M:%S%z')}",
            "",
            f"- Input markdown path: `{input_md}`",
            f"- Output HTML path: `{output_html}`",
            f"- Publish-safe validation result: {'warnings_found' if warnings else 'passed'}",
            "",
            "## Warnings",
            "",
            *([f"- {warning}" for warning in warnings] or ["- None"]),
            "",
            "## Boundary Confirmation",
            "",
            "- HTML export is local only.",
            "- No public publishing was performed.",
            "- `ai-investing-monitor/docs/index.html` was not updated.",
            "- The public docs intelligence path was not created or updated.",
            "",
        ]
    )


def append_migration_log(command: str, inputs: list[str], missing_optional: list[str], outputs: list[str], checks: list[str], counts: dict[str, int]) -> None:
    path = HUB / "docs/migration_log.md"
    entry = "\n".join(
        [
            "",
            f"## {datetime.now(TZ).date().isoformat()} - Phase 7A Source Policy and Local HTML Export",
            "",
            f"Timestamp: {datetime.now(TZ).strftime('%Y-%m-%dT%H:%M:%S%z')}",
            "",
            "Files changed:",
            "",
            "- `investment-intelligence-hub/docs/source_policy.md`",
            "- `investment-intelligence-hub/docs/architecture.md`",
            "- `investment-intelligence-hub/docs/schemas.md`",
            "- `investment-intelligence-hub/docs/verification.md`",
            "- `investment-intelligence-hub/scripts/run_hub_pipeline.py`",
            "",
            "Source policy created:",
            "",
            "- Added four-tier hierarchy covering Primary Sources, Daily Base / Core Financial News, ljg-invest Deep Research, and User-Captured X Posts.",
            "- Primary Source registry is intentionally deferred to Phase 8; `investment-intelligence-hub/memory/primary_sources.yaml` was not created.",
            "",
            "x_posts directory status:",
            "",
            f"- Current curated X inbox: `{rel(X_POSTS_ROOT)}`",
            "- Legacy or alternate folders `x-posts`, `manual_x`, `readwise`, and `x_timeline` are not current target inboxes if present; no automatic migration was performed.",
            "",
            "Script changes:",
            "",
            "- Added `--x-posts-dir` and default previous-day `x_posts/YYYY_MM_DD/` lookup.",
            "- Kept `--ljg-report` explicit-only and optional.",
            "- Added source-count flexibility for daily-only, daily plus ljg-invest, daily plus X, and all-source runs.",
            "- Added `--export-html` for local-only HTML output.",
            "- Added per-signal `source_type` and Tier 4 X corroboration validation.",
            "",
            "Command run:",
            "",
            f"- `{command}`",
            "",
            "Input files used:",
            "",
            *[f"- `{item}`" for item in inputs],
            "",
            "Missing optional inputs / warnings:",
            "",
            *([f"- {item}" for item in missing_optional] or ["- None"]),
            "",
            "Output files created:",
            "",
            *[f"- `{item}`" for item in outputs],
            "",
            f"Sources: {counts['sources']}. Signals: {counts['signals']}. Ticker impacts: {counts['ticker_impacts']}. Thesis impacts: {counts['thesis_impacts']}.",
            "",
            "Validation result:",
            "",
            *[f"- {check}" for check in checks],
            "- No production scripts were manually modified.",
            "",
            "Boundary confirmation:",
            "",
            "- Existing production scripts were not modified.",
            "- Existing `ai-investing-monitor` report generation logic was not changed.",
            "- `watchlists.yaml`, `themes.yaml`, and existing report files were not edited.",
            "- Existing daily reports, ljg-invest reports, and X converted files were not moved or rewritten.",
            "- The hub was not made canonical and was not linked from `docs/index.html`.",
            "- Durable memory thesis files were not updated.",
            "- No public publishing was performed.",
            "- No trading automation was created.",
            "- No trade instructions were generated.",
            "",
        ]
    )
    path.write_text(path.read_text(encoding="utf-8") + entry, encoding="utf-8")


def command_string(args: argparse.Namespace) -> str:
    parts = ["python3", "investment-intelligence-hub/scripts/run_hub_pipeline.py", "--date", args.date]
    parts += ["--mode", args.mode]
    if args.daily_report:
        parts += ["--daily-report", args.daily_report]
    if args.ljg_report:
        parts += ["--ljg-report", args.ljg_report]
    if args.x_md:
        parts += ["--x-md", args.x_md]
    if args.x_posts_dir:
        parts += ["--x-posts-dir", args.x_posts_dir]
    if args.export_html:
        parts += ["--export-html"]
    if args.skip_migration_log:
        parts += ["--skip-migration-log"]
    if args.dry_run:
        parts += ["--dry-run"]
    return " ".join(parts)


def run(args: argparse.Namespace) -> dict:
    if args.mode != "parallel":
        raise ValueError("Only --mode parallel is supported")
    X_POSTS_ROOT.mkdir(parents=True, exist_ok=True)
    daily, ljg, x_files, missing_optional = resolve_inputs(args)
    outputs = output_paths(args.date, args.export_html)
    output_rel = [rel(path) for path in outputs.values()]
    selected = [rel(daily)] + ([rel(ljg)] if ljg else []) + [rel(path) for path, _ in x_files]
    if args.dry_run:
        result = {
            "dry_run": True,
            "daily_report_exists": daily.exists(),
            "selected_input_files": selected,
            "input_existence": {item: (ROOT / item).exists() for item in selected},
            "missing_optional_inputs": missing_optional,
            "output_paths": output_rel,
            "writes_performed": False,
            "migration_log_updated": False,
        }
        if not daily.exists():
            result["error"] = f"Daily report is required and was not found: {rel(daily)}"
        print(json.dumps(result, indent=2, ensure_ascii=False))
        if not daily.exists():
            raise SystemExit(2)
        return result
    if not daily.exists():
        raise FileNotFoundError(f"Daily report is required and was not found: {rel(daily)}")
    ingested_at = datetime.now(TZ).strftime("%Y-%m-%dT%H:%M:%S%z")
    sources = source_records(args.date, ingested_at, daily, ljg, x_files)
    signals = signal_rows(args.date, sources)
    ticker_rows = ticker_impacts(args.date, signals)
    thesis_rows = thesis_impacts(args.date, signals)
    brief_text = brief(args.date, sources, signals, ticker_rows, thesis_rows)
    checks = validate_data(args.date, sources, signals, ticker_rows, thesis_rows, brief_text)
    counts = {
        "sources": len(sources),
        "signals": len(signals),
        "ticker_impacts": len(ticker_rows),
        "thesis_impacts": len(thesis_rows),
    }
    command = command_string(args)
    for key in ["sources", "signals", "ticker_impacts", "thesis_impacts", "brief", "notes", "validation"]:
        outputs[key].parent.mkdir(parents=True, exist_ok=True)
    write_jsonl(outputs["sources"], sources)
    write_jsonl(outputs["signals"], signals)
    write_jsonl(outputs["ticker_impacts"], ticker_rows)
    write_jsonl(outputs["thesis_impacts"], thesis_rows)
    outputs["brief"].write_text(brief_text, encoding="utf-8")
    outputs["notes"].write_text(notes(args.date, selected, missing_optional, output_rel, counts, command), encoding="utf-8")
    outputs["validation"].write_text(validation_markdown(args.date, command, selected, missing_optional, output_rel, counts, checks), encoding="utf-8")
    if args.export_html:
        html_warnings = publish_safe_warnings(brief_text)
        outputs["html"].parent.mkdir(parents=True, exist_ok=True)
        outputs["html"].write_text(markdown_to_html(brief_text, f"Investment Intelligence Brief - {args.date}"), encoding="utf-8")
        outputs["html_notes"].write_text(html_notes(args.date, rel(outputs["brief"]), rel(outputs["html"]), html_warnings), encoding="utf-8")
        if html_warnings:
            checks.append("HTML export completed with publish-safe warnings recorded.")
        else:
            checks.append("HTML export publish-safe validation passed.")
        outputs["validation"].write_text(validation_markdown(args.date, command, selected, missing_optional, output_rel, counts, checks), encoding="utf-8")
    if not args.skip_migration_log:
        append_migration_log(command, selected, missing_optional, output_rel, checks, counts)
    return {**counts, "outputs": output_rel, "missing_optional_inputs": missing_optional}


def main() -> None:
    args = parse_args()
    try:
        result = run(args)
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)
    if not args.dry_run:
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
